// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sentinel.Infrastructure.Persistence;

#nullable disable

namespace Sentinel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SentinelDbContext))]
    [Migration("20260908123433_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sentinel")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sentinel.Domain.Entities.EvaluationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actual")
                        .HasColumnType("jsonb");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<string>("Expected")
                        .HasColumnType("jsonb");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Passed");

                    b.ToTable("evaluation_results", "sentinel");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.EvaluationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Metrics")
                        .HasColumnType("jsonb");

                    b.Property<string>("ModelOrConfig")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "StartedAt");

                    b.ToTable("evaluation_runs", "sentinel");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Raw")
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("StepId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationId");

                    b.HasIndex("StepId");

                    b.ToTable("evidence", "sentinel");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Hypothesis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<decimal>("Score")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationId", "Rank");

                    b.ToTable("hypotheses", "sentinel");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("IncidentCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("sentinel.next_incident_code()");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IncidentCode")
                        .IsUnique();

                    b.HasIndex("StartedAt");

                    b.HasIndex("ServiceId", "Status");

                    b.ToTable("incidents", "sentinel");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Investigation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<int>("LlmCalls")
                        .HasColumnType("integer");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RouterIntent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RouterOutput")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ToolCalls")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalDurationMs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("Status");

                    b.ToTable("investigations", "sentinel");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.InvestigationStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationId", "Sequence")
                        .IsUnique();

                    b.ToTable("investigation_steps", "sentinel");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.ModelPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<Guid?>("InvestigationId")
                        .HasColumnType("uuid");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Output")
                        .HasColumnType("jsonb");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("ValidJson")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationId");

                    b.HasIndex("ModelName", "Purpose", "CalledAt");

                    b.ToTable("model_predictions", "sentinel");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Postmortem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedFiles")
                        .HasColumnType("jsonb");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IngestedToRag")
                        .HasColumnType("boolean");

                    b.Property<string>("LessonsLearned")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("RelevantCommits")
                        .HasColumnType("jsonb");

                    b.Property<string>("Structured")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("IngestedToRag");

                    b.ToTable("postmortems", "sentinel");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutionResult")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RootCauseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ToolArgs")
                        .HasColumnType("jsonb");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VerificationResult")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("InvestigationId");

                    b.HasIndex("RootCauseId");

                    b.HasIndex("Status");

                    b.ToTable("recommendations", "sentinel");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.RootCause", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Explanation")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Guid?>("HypothesisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("ValidatorConfidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("ValidatorOutput")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("HypothesisId");

                    b.HasIndex("InvestigationId");

                    b.ToTable("root_causes", "sentinel");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HealthUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MetricsJob")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RepoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("services", "sentinel");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.ToolCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Args")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDestructive")
                        .HasColumnType("boolean");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("StepId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalId");

                    b.HasIndex("InvestigationId");

                    b.HasIndex("IsDestructive")
                        .HasFilter("is_destructive = true");

                    b.HasIndex("StepId");

                    b.HasIndex("Tool", "CalledAt");

                    b.ToTable("tool_calls", "sentinel");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "sentinel");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.EvaluationResult", b =>
                {
                    b.HasOne("Sentinel.Domain.Entities.EvaluationRun", "Run")
                        .WithMany("Results")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Evidence", b =>
                {
                    b.HasOne("Sentinel.Domain.Entities.Investigation", "Investigation")
                        .WithMany("Evidence")
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sentinel.Domain.Entities.InvestigationStep", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Investigation");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Hypothesis", b =>
                {
                    b.HasOne("Sentinel.Domain.Entities.Investigation", "Investigation")
                        .WithMany("Hypotheses")
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investigation");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Incident", b =>
                {
                    b.HasOne("Sentinel.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sentinel.Domain.Entities.Service", "Service")
                        .WithMany("Incidents")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Investigation", b =>
                {
                    b.HasOne("Sentinel.Domain.Entities.Incident", "Incident")
                        .WithMany("Investigations")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.InvestigationStep", b =>
                {
                    b.HasOne("Sentinel.Domain.Entities.Investigation", "Investigation")
                        .WithMany("Steps")
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investigation");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.ModelPrediction", b =>
                {
                    b.HasOne("Sentinel.Domain.Entities.Investigation", "Investigation")
                        .WithMany()
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Investigation");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Postmortem", b =>
                {
                    b.HasOne("Sentinel.Domain.Entities.Incident", "Incident")
                        .WithMany("Postmortems")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("Sentinel.Domain.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sentinel.Domain.Entities.Investigation", "Investigation")
                        .WithMany()
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sentinel.Domain.Entities.RootCause", "RootCause")
                        .WithMany("Recommendations")
                        .HasForeignKey("RootCauseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Investigation");

                    b.Navigation("RootCause");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.RootCause", b =>
                {
                    b.HasOne("Sentinel.Domain.Entities.Hypothesis", "Hypothesis")
                        .WithMany()
                        .HasForeignKey("HypothesisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sentinel.Domain.Entities.Investigation", "Investigation")
                        .WithMany("RootCauses")
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hypothesis");

                    b.Navigation("Investigation");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.ToolCall", b =>
                {
                    b.HasOne("Sentinel.Domain.Entities.Recommendation", "Approval")
                        .WithMany()
                        .HasForeignKey("ApprovalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sentinel.Domain.Entities.Investigation", "Investigation")
                        .WithMany("ToolCallRecords")
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sentinel.Domain.Entities.InvestigationStep", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Approval");

                    b.Navigation("Investigation");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.EvaluationRun", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Incident", b =>
                {
                    b.Navigation("Investigations");

                    b.Navigation("Postmortems");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Investigation", b =>
                {
                    b.Navigation("Evidence");

                    b.Navigation("Hypotheses");

                    b.Navigation("RootCauses");

                    b.Navigation("Steps");

                    b.Navigation("ToolCallRecords");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.RootCause", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("Sentinel.Domain.Entities.Service", b =>
                {
                    b.Navigation("Incidents");
                });
#pragma warning restore 612, 618
        }
    }
}
