using FluentAssertions;
using Microsoft.Extensions.Configuration;
using Sentinel.Infrastructure.Ai;
using Xunit;

namespace Sentinel.UnitTests.Ai;

/// <summary>
/// The approval token, pinned to the bytes Python produces.
/// </summary>
/// <remarks>
/// <para>
/// This format is written twice — here and in <c>ai-service/mcp_client/approval.py</c> — and read
/// by three processes. There is no runtime that would catch a drift: a payload whose keys were
/// serialised in a different order still signs, still parses, and fails verification everywhere
/// with "the signature is not valid", which reads like an attack.
/// </para>
/// <para>
/// So the vector below was generated by the Python implementation and is checked byte for byte.
/// If this test fails after a change to either side, the two are no longer the same scheme.
/// </para>
/// </remarks>
public sealed class ApprovalTokenServiceTests
{
    private const string Secret = "cross-language-test-secret";
    private const string Recommendation = "11111111-1111-1111-1111-111111111111";
    private const string Tool = "docker-mcp/restart_container";
    private const string Arguments = """{"name":"sentinel-orders"}""";

    /// <summary>Generated by <c>ApprovalTokens.issue</c> with the values above and exp 1789000000.</summary>
    private const string PythonToken =
        "eyJhcmdzIjoiNzUwMGEzZjk1NzY2MjAzYWY4Y2Y2OGQyNWY0ZjllODE0ZDVhMjdjNTBjM2ViN2MzZTZjYTM0M2U5" +
        "YmYwYjMwOCIsImJ5Ijoib3BlcmF0b3JAc2VudGluZWwiLCJleHAiOjE3ODkwMDAwMDAsInJlYyI6IjExMTExMTEx" +
        "LTExMTEtMTExMS0xMTExLTExMTExMTExMTExMSIsInRvb2wiOiJkb2NrZXItbWNwL3Jlc3RhcnRfY29udGFpbmVy" +
        "IiwidiI6InNhMSJ9.cZ38sajdXC0i2ZSoUG-1bt49AQQyCK_oOYifVdup3vM";

    /// <summary>From <c>hash_arguments({"name": "sentinel-orders"})</c>.</summary>
    private const string PythonArgumentsHash =
        "7500a3f95766203af8cf68d25f4f9e814d5a27c50c3eb7c3e6ca343e9bf0b308";

    private static ApprovalTokenService Service(string? secret = Secret) =>
        new(new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                [ApprovalTokenService.ConfigurationKey] = secret,
            })
            .Build());

    [Fact]
    public void Issues_the_same_token_python_does()
    {
        var token = Service().Issue(
            Guid.Parse(Recommendation),
            Tool,
            Arguments,
            "operator@sentinel",
            DateTimeOffset.FromUnixTimeSeconds(1_789_000_000));

        token.Should().Be(PythonToken);
    }

    [Fact]
    public void Hashes_arguments_the_same_way_python_does()
    {
        ApprovalTokenService.HashArguments(Arguments).Should().Be(PythonArgumentsHash);
    }

    [Fact]
    public void Key_order_in_the_stored_arguments_does_not_change_the_hash()
    {
        // The agent wrote this JSON and the order it chose is not something the approval can
        // depend on: both sides sort before hashing.
        ApprovalTokenService.HashArguments("""{"b":"two","a":1}""")
            .Should()
            .Be(ApprovalTokenService.HashArguments("""{"a":1,"b":"two"}"""));
    }

    [Fact]
    public void A_number_and_the_string_of_it_are_different_calls()
    {
        ApprovalTokenService.HashArguments("""{"tail":100}""")
            .Should()
            .NotBe(ApprovalTokenService.HashArguments("""{"tail":"100"}"""));
    }

    [Fact]
    public void Changing_one_argument_changes_the_token()
    {
        var service = Service();
        var expiry = DateTimeOffset.FromUnixTimeSeconds(1_789_000_000);

        var orders = service.Issue(Guid.Parse(Recommendation), Tool, Arguments, "op", expiry);
        var payments = service.Issue(
            Guid.Parse(Recommendation), Tool, """{"name":"sentinel-payments"}""", "op", expiry);

        orders.Should().NotBe(payments);
    }

    [Fact]
    public void Without_a_secret_nothing_can_be_issued()
    {
        var service = Service(secret: null);

        service.IsConfigured.Should().BeFalse();
        service.Invoking(s => s.Issue(Guid.NewGuid(), Tool, Arguments, "op"))
            .Should()
            .Throw<InvalidOperationException>();
    }

    [Fact]
    public void Unparseable_arguments_hash_as_an_empty_object()
    {
        // A recommendation whose arguments will not parse cannot be executed with them, and the
        // AI service's own hash of `{}` will refuse the call. Better than throwing here, where
        // the caller is a person clicking approve.
        ApprovalTokenService.HashArguments("not json at all")
            .Should()
            .Be(ApprovalTokenService.HashArguments(null));
    }
}
