using Microsoft.EntityFrameworkCore;
using Sentinel.Domain;
using Sentinel.Domain.Entities;

namespace Sentinel.Application.Common;

/// <summary>
/// The database as the application layer sees it.
/// </summary>
/// <remarks>
/// Exists so handlers can be unit-tested against an in-memory context without referencing
/// Infrastructure. Deliberately not a repository per entity: EF Core's DbSet already is one, and
/// a second layer of wrappers would buy nothing here.
/// </remarks>
public interface ISentinelDbContext
{
    DbSet<Service> Services { get; }

    DbSet<User> Users { get; }

    DbSet<Incident> Incidents { get; }

    DbSet<Investigation> Investigations { get; }

    DbSet<InvestigationStep> InvestigationSteps { get; }

    DbSet<Evidence> Evidence { get; }

    DbSet<Hypothesis> Hypotheses { get; }

    DbSet<RootCause> RootCauses { get; }

    DbSet<Recommendation> Recommendations { get; }

    DbSet<Postmortem> Postmortems { get; }

    DbSet<ToolCall> ToolCalls { get; }

    DbSet<ModelPrediction> ModelPredictions { get; }

    DbSet<EvaluationRun> EvaluationRuns { get; }

    DbSet<EvaluationResult> EvaluationResults { get; }

    Task<int> SaveChangesAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Reloads an entity from the database. Needed after inserting an incident, because
    /// <c>incident_code</c> is generated by a database default and the in-memory instance does
    /// not have it until it is read back.
    /// </summary>
    Task ReloadAsync<TEntity>(TEntity entity, CancellationToken cancellationToken = default)
        where TEntity : class;
}

public interface IPasswordHasher
{
    string Hash(string password);

    bool Verify(string password, string hash);
}

public interface IJwtTokenService
{
    /// <summary>Issues an access token for a user.</summary>
    /// <returns>The token and the instant it expires.</returns>
    (string Token, DateTimeOffset ExpiresAt) CreateToken(Guid userId, string username, UserRole role);
}

/// <summary>Who is making the current request. Null values mean an unauthenticated caller.</summary>
public interface ICurrentUser
{
    Guid? UserId { get; }

    string? Username { get; }

    UserRole? Role { get; }
}
